### ISSUE TITLE
Install uIntra 2.0.1 fails

### ISSUE THREAD

**Issue by ClaesYlving** [Uintra/Uintra#124]
When running UIntra 2.0.1 on a clean install in VS2019 it always fails in installation. I have SqlExpress2019 locally and I have tried with both IIS locally and IISExpress. Errormsg:

Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.NullReferenceException: Object reference not set to an instance of an object.
  at Uintra20.Core.Updater.MigrationExecutor.Run()
  at Uintra20.UintraApplicationComponent.Initialize()
  at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 188

**Comment by denprodan** [comment]
Hi @ClaesYlving. Do you install Umbraco with Machine Key?

**Comment by KeylinxTobias** [comment]
Hi, Tobias here, collegue with Claes,

Yes machinekey is part of the web.config

**Comment by denprodan** [comment]
Hi @KeylinxTobias 
UIntra 2.0.1? We published only 2.0 version to the nuget
Please check this  https://github.com/Uintra/Uintra/issues/120 as I can see you have the same problem

**Comment by vmatsukatov** [comment]
hi @KeylinxTobias  please, add the new task with details we mentioned in the last comment to you if issue is still topical. we will close that one due to no response and new one uintra version available
